/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logincheck;

import static java.awt.EventQueue.invokeLater;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HİLAL
 */
public class studentCheckin extends javax.swing.JFrame {

    String gender;
    
    /**
     * Creates new form studentCeckin
     */
    public studentCheckin() {
        
        initComponents();
        showUser();
        
    }
    
    public ArrayList <User> userList() {
        ArrayList<User> userList = new ArrayList<>();
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName = dbtest;IntegratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String query = "SELECT*FROM users";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            User user ;
            while(rs.next()) {
                user = new User(rs.getInt("uid"), rs.getString("name"), rs.getString("gender"), 
                        rs.getString("address"), rs.getString("department"), rs.getString("course"));
                userList.add(user);
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userList;
    }
    public void showUser() {
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)j_tableDisplay.getModel();
        Object[] row = new Object[6];
        
        for(int i = 0;i < list.size(); i++) {
        row[0] = list.get(i).getuid();
        row[1] = list.get(i).getname();
        row[2] = list.get(i).getgender();
        row[3] = list.get(i).getaddress();
        row[4] = list.get(i).getdepartment();
        row[5] = list.get(i).getcourse();

        model.addRow(row);

                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        java = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        pyhton = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_tableDisplay = new javax.swing.JTable();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(908, 528));

        jLabel.setText("AD/SOYAD");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel2.setText("CİNSİYET");

        jLabel3.setText("ADRES");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        jLabel4.setText("BÖLÜM");

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select the Department--", "Bilgisayar Mühendisliği", "Endüstri Mühendisliği", "Yönetim Bilişim sistemleri", "Elektrik-Elektronik Mühendisliği", "İşletme Enformatiği" }));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        jLabel5.setText("KURS");

        java.setText("JAVA");

        c.setText("C");

        pyhton.setText("PYHTON");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ÖĞRENCİ KAYIT SİSTEMİ");

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        j_tableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "uid", "name", "gender", "address", "department", "course"
            }
        ));
        j_tableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_tableDisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(j_tableDisplay);

        buttonGroup1.add(female);
        female.setText("KADIN");

        buttonGroup1.add(male);
        male.setText("ERKEK");

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(22, 22, 22)))
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(java)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pyhton))
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(female)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(male))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(female)
                            .addComponent(male))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(java)
                                .addComponent(c)
                                .addComponent(pyhton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(save))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update)
                            .addComponent(delete)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        
        try{

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName = dbtest;IntegratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into users (name,gender,address,department,course) values(?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, name.getText());
            
            if(female.isSelected()) {
                 gender = "female";
            }else if(male.isSelected()) {
                 gender = "male";
            }
            pst.setString(2, gender);
            pst.setString(3, address.getText());
           
            String dept = "";
            dept = department.getSelectedItem().toString();
            pst.setString(4, dept);
            
            String course = "";
            if(java.isSelected()) {
                course += java.getText() + "";
            }
            if(c.isSelected()) {
                course += c.getText() + "";
            }
            if(pyhton.isSelected()) {
                course += pyhton.getText() + "";
            }
            pst.setString(5, course);
      
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insert Successfulled");
            con.close();
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        name.setText("");
        buttonGroup1.clearSelection();
        address.setText("");
        department.setSelectedIndex(0);
        java.isDisplayable();
        c.isDisplayable();
        pyhton.isDisplayable();
        
    }//GEN-LAST:event_resetActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void j_tableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_tableDisplayMouseClicked
        // TODO add your handling code here:
        int i = j_tableDisplay.getSelectedRow();
        
        TableModel model = j_tableDisplay.getModel();
        name.setText(model.getValueAt(i, 1).toString());
        String gender1 = model.getValueAt(i, 2).toString();
        if(gender1.equalsIgnoreCase("female"))
        {
            female.setSelected(true);
        }
        else
        {
            male.setSelected(true);
        }
        
        address.setText(model.getValueAt(i, 3).toString());
        
        String department1 = model.getValueAt(i, 4).toString();
        switch(department1) {
            case "Bilgisayar Mühendisliği":
                department.setSelectedIndex(0);
                break;
            case "Endüstri Mühendisliği":
                department.setSelectedIndex(1);
                break;
            case "Yönetim Bilisim Sistemleri":
                department.setSelectedIndex(2);
                break;
            case "Elektrik-Elektronik Mühendisliği":
                department.setSelectedIndex(3);
            case "İşletme Enformatiği":
                department.setSelectedIndex(4);
                break;
            
            
        }
        
        String course = model.getValueAt(i, 5).toString();
        switch(course) {
            case "JAVA":
                java.setSelected(true);
                c.setSelected(false);
                pyhton.setSelected(false);
                break;
            case "C":
                c.setSelected(true);
                java.setSelected(false);
                pyhton.setSelected(false);
                break;
            default:
                c.setSelected(true);
                java.setSelected(true);
                pyhton.setSelected(true);
                
        }
        
        
    }//GEN-LAST:event_j_tableDisplayMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName = dbtest;IntegratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            
            int row = j_tableDisplay.getSelectedRow();
            String value = (j_tableDisplay.getModel().getValueAt(row, 0).toString());
            String query4 = "update users set name = ? , gender = ?, address = ?, department = ?, course = ?"
                    + "where uid = " + value;
            PreparedStatement pst = con.prepareStatement(query4);
            pst.setString(1, name.getText());
           
             if(female.isSelected()) {
                 gender = "female";
            }else if(male.isSelected()) {
                 gender = "male";
            }
            pst.setString(2, gender);
            pst.setString(3, address.getText());
           
            String dept = "";
            dept = department.getSelectedItem().toString();
            pst.setString(4, dept);;
            
            String course = "";
            if(java.isSelected()) {
                course += java.getText() + "";
            }
            if(c.isSelected()) {
                course += c.getText() + "";
            }
            if(pyhton.isSelected()) {
                course += pyhton.getText() + "";
            }
            pst.setString(5, course);
            DefaultTableModel model = (DefaultTableModel)j_tableDisplay.getModel();
            model.setRowCount(0);
            showUser();
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update succesfullied");
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete?","DELETE", JOptionPane.YES_NO_OPTION);
        
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName = dbtest;IntegratedSecurity=true";
            Connection con = DriverManager.getConnection(url);
            
            int row = j_tableDisplay.getSelectedRow();

            String value = (j_tableDisplay.getModel().getValueAt(row, 0)).toString();
            
            String query5 = "delete from users where uid = " + value;
            PreparedStatement pst = con.prepareStatement(query5);
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        invokeLater(new Runnable() {
            public void run() {
                new studentCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox c;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_tableDisplay;
    private javax.swing.JCheckBox java;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox pyhton;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
